version: "2"
services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=baat
      - MYSQL_USER=baat_user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  baat-user:
    build: baat-user/
    image: sachingoyaldocker/baat-user
    links:
      - mysqldb
    ports:
      - '8081:8081'
    environment:
      - SERVER_PORT=8081
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=baat_user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=baat
      - DATABASE_PORT=3306
      - DATABASE_INITIALISE=true

  baat-web:
    build: baat-web/
    image: sachingoyaldocker/baat-web
    links:
      - baat-user
    ports:
      - '8082:8082'
    environment:
      - SERVER_PORT=8082
      - USER_SERVICE_URI=http://baat-user:8081

  baat-ws:
    build: baat-ws/
    image: sachingoyaldocker/baat-ws
    links:
      - rabbitmq:management
      - baat-user
    ports:
      - '8083:8083'
    environment:
      - SERVER_PORT=8083
      - RABBITMQ_HOST=rabbitmq
      - USER_SERVICE_URI=http://baat-user:8081

  baat-chat:
    build: baat-chat/
    image: sachingoyaldocker/baat-chat
    links:
      - rabbitmq:management
      - baat-user
    ports:
      - '8084:8084'
    environment:
      - SERVER_PORT=8084
      - RABBITMQ_HOST=rabbitmq
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=baat_user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=baat
      - DATABASE_PORT=3306
      - DATABASE_INITIALISE=true
      - USER_SERVICE_URI=http://baat-user:8081

